workflows:
  # ===================================================================
  # ============ WORKFLOW UNIFICADO: ANDROID + WEB ====================
  # ===================================================================
  build-android-and-web:
    name: 'Build Completo (Release APK + Web App)'
    instance_type: mac_mini_m2
    environment:
      # =================== INÍCIO DA CORREÇÃO ===================
      flutter: 3.35.4
      # =================== FIM DA CORREÇÃO ======================
      groups:
        - Borracharia # Grupo que contém suas variáveis de ambiente
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
        - pattern: develop
          include: true
    scripts:
      # ... (o resto do seu script permanece o mesmo)
      - name: Set up Android credentials
        script: |
          set -e
          echo "Decodificando credenciais Android..."
          echo $GCLOUD_KEY_FILE | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/android/app/keystore.jks
          cat > $CM_BUILD_DIR/android/key.properties <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_ALIAS_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=keystore.jks
          EOF
          echo "✅ Credenciais Android configuradas com sucesso!"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android Release APK (Signed)
        script: |
          echo "Iniciando build do APK de Release assinado..."
          flutter build apk --release
      - name: Build Flutter Web
        script: |
          echo "Iniciando build do Flutter Web..."
          flutter build web --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/web/**

  # ===================================================================
  # =========== WORKFLOW DE DEBUG (PARA TESTES RÁPIDOS) ===============
  # ===================================================================
  debug-build:
    name: 'Build de Debug (Android APK)'
    instance_type: mac_mini_m2
    environment:
      # =================== INÍCIO DA CORREÇÃO ===================
      flutter: 3.35.4
      # =================== FIM DA CORREÇÃO ======================
      groups:
        - Borracharia
    scripts:
      # ... (o resto do seu script permanece o mesmo)
      - name: Set up Google Services
        script: |
          echo "Decodificando google-services.json..."
          echo $GCLOUD_KEY_FILE | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
          echo "✅ google-services.json configurado."
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android Debug APK
        script: |
          echo "Iniciando build do APK de Debug..."
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  # ===================================================================
  # ============ WORKFLOW DE PROFILE (PARA DIAGNÓSTICO) ==========
  # ===================================================================
  profile-build:
    name: 'Build de Profile (Diagnóstico Android)'
    instance_type: mac_mini_m2
    environment:
      # =================== INÍCIO DA CORREÇÃO ===================
      flutter: 3.35.4
      # =================== FIM DA CORREÇÃO ======================
      groups:
        - Borracharia
    scripts:
      # ... (o resto do seu script permanece o mesmo)
      - name: Set up Google Services
        script: |
          echo "Decodificando google-services.json..."
          echo $GCLOUD_KEY_FILE | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
          echo "✅ google-services.json configurado."
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android Profile APK
        script: |
          echo "Iniciando build do APK de Profile para diagnóstico..."
          flutter build apk --profile
    artifacts:
      - build/app/outputs/flutter-apk/app-profile.apk
