name: vitrine_borracharia
description: 'Aplicativo de E-commerce: Vitrine digital para borracharia com gestão de produtos e pedidos.'
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
 # speech_to_text: ^6.6.2
  
  # REMOVIDO: Firebase Dependencies
  # firebase_core: ^2.27.1
  # firebase_auth: ^4.17.9
  # cloud_firestore: ^4.15.9

  # Estado e armazenamento
  provider: ^6.1.2
  shared_preferences: ^2.2.3  # ESSENCIAL para JWT tokens

  # Comunicação com API
  http: ^1.1.0
  
  # Upload de imagens e permissões (VERSÕES ATUALIZADAS PARA CORRIGIR O BUILD)
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  permission_handler: ^11.3.1
  crypto: ^3.0.3
  path_provider: ^2.1.2

  # UI e formatação
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  lucide_icons_flutter: ^3.1.0
  record: ^5.0.5

  # Voice recognition - MOVIDO PARA DEPENDENCIES
 # speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images_png/app_icon.png" 
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images_png/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    # Diretórios de assets
    - assets/images_png/
    - assets/audio/
    - assets/fonts/

  fonts:
    - family: Gothic
      fonts:
        - asset: assets/fonts/gothic.ttf
    - family: Digital
      fonts:
        - asset: assets/fonts/digital.ttf
